### ISSUE TITLE
Not starting CS:GO

### ISSUE THREAD

**Issue by lenovouser** [aboltunov/docker-csgo#1]
@aboltunov I am getting:

```
csgo-1    | Connecting anonymously to Steam Public...Logged in OK
csgo-1    | Waiting for license info...OK
csgo-1    |  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
csgo-1    | Error! App '740' state is 0x602 after update job.
csgo-1    | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
csgo-1    | [----] Verifying installation...
csgo-1    | [----] !!! Fatal Error: Steamcmd needs 250MB of free disk space to update.
```

when I try to start the server. Is there any way to fix this?

**Comment by aboltunov** [comment]
It looks like you're just low on disk space, right? Not sure why the csgo server requires this much space but it uses around 10GB for me.

**Comment by lenovouser** [comment]
I have 1.8 TB free. Seems to be related to https://github.com/ValveSoftware/steam-for-linux/issues/4824, not sure though
